name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make install

    - name: Formatting 
      run: make format

   
