name: Pipeline.yml

on:
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

        - name: Install Dependies
          run: | 
            make install

        - name: Formatting
          run: |
            make format